spring:
  datasource:
    url: jdbc:postgresql://${db.host:127.0.0.1}:${db.port:5432}/dostock
    username: ${db.user:dostock}
    password: ${db.pass:dostock}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
storage:
  path: ${storage.path:"/Users/matheusmarques/Documents/Desenv/Estudo/dostock/files"}